# Generated by Django 5.2.4 on 2025-08-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='is_current_month',
        ),
        migrations.AddField(
            model_name='kakeibo',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='収支名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='balance',
            field=models.BooleanField(default=False, verbose_name='収支区分'),
        ),
    ]
