# Generated by Django 5.2.4 on 2025-08-04 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_remove_budget_is_current_month_kakeibo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakeibo',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='日付'),
        ),
    ]
