# Generated by Django 5.2.4 on 2025-08-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
