# Generated by Django 5.2.4 on 2025-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakeibo',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '収入'), (2, '支出')], default=2),
        ),
    ]
