# Generated by Django 5.2.4 on 2025-08-05 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_kakeibo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='records.category', verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='records.category', verbose_name='カテゴリ'),
        ),
    ]
