# Generated by Django 5.2.4 on 2025-08-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_kakeibo_category_alter_subscription_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kakeibo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.category', verbose_name='カテゴリ'),
        ),
    ]
