# Generated by Django 5.2.4 on 2025-08-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_kakeibo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '収入'), (2, '支出')], default=2),
        ),
    ]
