from rest_framework_simplejwt.views import TokenObtainPairView
from records.serializers.custom_token_serializer import CustomTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer